// app/components/scroll-to-top.tsx
'use client';

import { useEffect, useState } from 'react';

export default function ScrollToTop() {
    const [isVisible, setIsVisible] = useState(false);
    const scrollThreshold = 300;

    useEffect(() => {
        const toggleVisibility = () => {
            if (window.scrollY > scrollThreshold) {
                setIsVisible(true);
            } else {
                setIsVisible(false);
            }
        };

        window.addEventListener('scroll', toggleVisibility);

        return () => {
            window.removeEventListener('scroll', toggleVisibility);
        };
    }, []);

    const scrollToTop = () => {
        window.scrollTo({
            top: 0,
            behavior: 'smooth',
        });
    };

    return (
        <button
            onClick={scrollToTop}
            className={`${isVisible ? "opacity-100" : "opacity-0"} fixed bottom-8 right-8 bg-white/10 hover:bg-white/20 backdrop-blur-sm text-white p-3 rounded-full shadow-lg transition-all duration-300 z-50 print:hidden`}
            aria-label="Scroll to top"
        >
            <svg
                xmlns="http://www.w3.org/2000/svg"
                className="h-6 w-6"
                fill="none"
                viewBox="0 0 24 24"
                stroke="currentColor"
            >
                <path
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    strokeWidth={2}
                    d="M5 10l7-7m0 0l7 7m-7-7v18"
                />
            </svg>
        </button>
    );
}

// sveltekit/src/lib/components/ScrollToTop.svelte
<script lang="ts">
	import { onMount } from 'svelte';

	let isVisible = $state(false);

	onMount(() => {
		const toggleVisibility = () => {
			isVisible = window.scrollY > 300;
		};

		toggleVisibility();
		window.addEventListener('scroll', toggleVisibility, { passive: true });

		return () => window.removeEventListener('scroll', toggleVisibility);
	});

	function scrollToTop() {
		window.scrollTo({ top: 0, behavior: 'smooth' });
	}
</script>

<button
	type="button"
	onclick={scrollToTop}
	class="fixed right-8 bottom-8 z-50 rounded-full bg-white/10 p-3 text-white shadow-lg backdrop-blur-sm transition-all duration-300 hover:bg-white/20 print:hidden {isVisible
		? 'opacity-100'
		: 'pointer-events-none opacity-0'}"
	aria-label="Scroll to top"
	aria-hidden={!isVisible}
	tabindex={isVisible ? 0 : -1}
>
	<svg class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
		<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 10l7-7m0 0l7 7m-7-7v18" />
	</svg>
</button>
