// sveltekit/src/lib/components/Card.svelte
<script lang="ts">
	let { children } = $props();
	let mouseX = $state(0);
	let mouseY = $state(0);

	function trackPointer(event: PointerEvent) {
		const bounds = (event.currentTarget as HTMLDivElement).getBoundingClientRect();
		mouseX = event.clientX - bounds.left;
		mouseY = event.clientY - bounds.top;
	}
</script>

<div
	role="group"
	onpointermove={trackPointer}
	style:--mouse-x={`${mouseX}px`}
	style:--mouse-y={`${mouseY}px`}
	class="group relative h-full w-full overflow-hidden rounded-xl border border-zinc-600 duration-700 hover:border-zinc-400/50 hover:bg-zinc-800/10 md:gap-8"
>
	<div class="pointer-events-none">
		<div
			class="absolute inset-0 z-0 mask-[linear-gradient(black,transparent)] transition duration-1000"
		></div>
		<div
			class="pointer-glow absolute inset-0 z-10 bg-linear-to-br via-zinc-100/10 opacity-100 transition duration-1000 group-hover:opacity-50"
		></div>
		<div
			class="pointer-glow absolute inset-0 z-10 opacity-0 mix-blend-overlay transition duration-1000 group-hover:opacity-100"
		></div>
	</div>
	{@render children()}
</div>

<style>
	.pointer-glow {
		-webkit-mask-image: radial-gradient(
			240px at var(--mouse-x) var(--mouse-y),
			white,
			transparent
		);
		mask-image: radial-gradient(240px at var(--mouse-x) var(--mouse-y), white, transparent);
	}
</style>

// app/components/card.tsx
"use client";
import {
	motion,
	useMotionTemplate,
	useMotionValue,
	useSpring,
} from "framer-motion";

import { MouseEventHandler, PropsWithChildren } from "react";

export const Card: React.FC<PropsWithChildren> = ({ children }) => {
	const mouseX = useSpring(0, { stiffness: 500, damping: 100 });
	const mouseY = useSpring(0, { stiffness: 500, damping: 100 });

	function onMouseMove({ currentTarget, clientX, clientY }: any) {
		const { left, top } = currentTarget.getBoundingClientRect();
		mouseX.set(clientX - left);
		mouseY.set(clientY - top);
	}
	const maskImage = useMotionTemplate`radial-gradient(240px at ${mouseX}px ${mouseY}px, white, transparent)`;
	const style = { maskImage, WebkitMaskImage: maskImage };

	return (
		<div
			onMouseMove={onMouseMove}
			className="overflow-hidden relative w-full h-full duration-700 border rounded-xl hover:bg-zinc-800/10 group md:gap-8 hover:border-zinc-400/50 border-zinc-600 "
		>
			<div className="pointer-events-none">
				<div className="absolute inset-0 z-0  transition duration-1000 [mask-image:linear-gradient(black,transparent)]" />
				<motion.div
					className="absolute inset-0 z-10  bg-gradient-to-br opacity-100  via-zinc-100/10  transition duration-1000 group-hover:opacity-50 "
					style={style}
				/>
				<motion.div
					className="absolute inset-0 z-10 opacity-0 mix-blend-overlay transition duration-1000 group-hover:opacity-100"
					style={style}
				/>
			</div>

			{children}
		</div>
	);
};
