// sveltekit/src/lib/components/Nav.svelte
<script lang="ts">
	import { Hexagon, Menu, X } from 'lucide-svelte';
	const links = [
		{ href: '/', label: 'Index' },
		{ href: '/projects', label: 'Projects' },
		{ href: '/profile', label: 'Profile' },
		{ href: '/posts', label: 'Posts' },
		{ href: '/library', label: 'Library' },
		{ href: '/speaking', label: 'Speaking' },
		{ href: '/mentoring', label: 'Mentoring' },
		{ href: '/lamp', label: 'Lamp' },
		{ href: '/contact', label: 'Contact' }
	];
	let isMenuOpen = $state(false);
	let isIntersecting = $state(true);
	let header: HTMLElement;
	let menu: HTMLDivElement;
	let button: HTMLButtonElement;
	let background = $derived(
		isMenuOpen ? 'bg-zinc-900/95' : isIntersecting ? 'bg-zinc-800/40' : 'bg-zinc-800/70'
	);

	$effect(() => {
		const observer = new IntersectionObserver(([entry]) => {
			isIntersecting = entry.isIntersecting;
		});
		observer.observe(header);
		return () => observer.disconnect();
	});

	$effect(() => {
		if (!isMenuOpen) return;
		const closeOnOutsideClick = (event: MouseEvent) => {
			const target = event.target as Node;
			if (!menu.contains(target) && !button.contains(target)) isMenuOpen = false;
		};
		document.addEventListener('mousedown', closeOnOutsideClick);
		return () => document.removeEventListener('mousedown', closeOnOutsideClick);
	});
</script>

<header bind:this={header} class="absolute inset-x-0 top-0 h-px">
	<div
		bind:this={menu}
		class="fixed inset-x-4 top-4 z-50 mx-auto rounded-2xl border border-white/10 shadow-[inset_0_1px_1px_0_hsla(0,0%,100%,.15)] backdrop-blur duration-200 sm:container sm:inset-x-0 {background}"
	>
		<div class="flex items-center justify-between p-6">
			<a href="/" class="text-zinc-300 duration-200 hover:text-zinc-100" aria-label="Home">
				<Hexagon class="h-6 w-6" />
			</a>
			<div class="hidden justify-around gap-8 text-sm md:flex">
				{#each links as link}
					<a href={link.href} class="text-zinc-400 duration-200 hover:text-zinc-100">
						{link.label}
					</a>
				{/each}
			</div>
			<button
				bind:this={button}
				type="button"
				class="text-zinc-400 hover:text-zinc-100 md:hidden"
				aria-label="Toggle menu"
				aria-expanded={isMenuOpen}
				onclick={() => (isMenuOpen = !isMenuOpen)}
			>
				{#if isMenuOpen}<X class="h-6 w-6" />{:else}<Menu class="h-6 w-6" />{/if}
			</button>
		</div>
		{#if isMenuOpen}
			<div class="space-y-4 px-6 pb-6 md:hidden">
				{#each links as link}
					<a
						href={link.href}
						class="block text-zinc-400 duration-200 hover:text-zinc-100"
						onclick={() => (isMenuOpen = false)}
					>
						{link.label}
					</a>
				{/each}
			</div>
		{/if}
	</div>
</header>

// app/components/nav.tsx
"use client";
import { Hexagon, Menu, X } from "lucide-react";
import Link from "next/link";
import React, { useEffect, useRef, useState } from "react";

const links = [
	{ href: "/", label: "Index" },
	{ href: "/projects", label: "Projects" },
	{ href: "/profile", label: "Profile" },
	{ href: "/posts", label: "Posts" },
	{ href: "/library", label: "Library" },
	{ href: "/speaking", label: "Speaking" },
	{ href: "/mentoring", label: "Mentoring" },
	{ href: "/lamp", label: "Lamp" },
	{ href: "/contact", label: "Contact" },
];

const useIntersectionObserver = (ref: React.RefObject<HTMLElement>) => {
	const [isIntersecting, setIntersecting] = useState(true);

	useEffect(() => {
		if (!ref.current) return;

		const observer = new IntersectionObserver(([entry]) =>
			setIntersecting(entry.isIntersecting),
		);

		observer.observe(ref.current);
		return () => observer.disconnect();
	}, [ref]);

	return isIntersecting;
};

const useClickOutside = (
	isOpen: boolean,
	onClose: () => void,
	excludeRefs: React.RefObject<HTMLElement>[]
) => {
	useEffect(() => {
		const handleClickOutside = (event: MouseEvent) => {
			const clickedOutside = excludeRefs.every(
				ref => ref.current && !ref.current.contains(event.target as Node)
			);

			if (clickedOutside) {
				onClose();
			}
		};

		if (isOpen) {
			document.addEventListener('mousedown', handleClickOutside);
		}

		return () => {
			document.removeEventListener('mousedown', handleClickOutside);
		};
	}, [isOpen, onClose, excludeRefs]);
};

const NavigationLink: React.FC<{
	href: string;
	onClick?: () => void;
	children: React.ReactNode;
	isMobile?: boolean;
}> = ({
	href,
	children,
	onClick,
	isMobile = false,
}) => (
		<Link
			href={href}
			className={`duration-200 text-zinc-400 hover:text-zinc-100 ${isMobile ? 'block' : ''}`}
			onClick={onClick}
		>
			{children}
		</Link>
	);

const DesktopNavigation = () => (
	<div className="hidden md:flex justify-around gap-8 text-sm">
		{links.map(({ href, label }) => (
			<NavigationLink key={href} href={href}>
				{label}
			</NavigationLink>
		))}
	</div>
);

const MobileNavigation: React.FC<{ isOpen: boolean; onClose: () => void }> = ({
	isOpen,
	onClose,
}) => {
	if (!isOpen) return null;

	return (
		<div className="md:hidden px-6 pb-6 space-y-4">
			{links.map(({ href, label }) => (
				<NavigationLink key={href} href={href} onClick={onClose} isMobile>
					{label}
				</NavigationLink>
			))}
		</div>
	);
};

export const Navigation: React.FC = () => {
	const headerRef = useRef<HTMLElement>(null);
	const menuRef = useRef<HTMLDivElement>(null);
	const buttonRef = useRef<HTMLButtonElement>(null);
	const [isMenuOpen, setIsMenuOpen] = useState(false);

	const isIntersecting = useIntersectionObserver(headerRef);
	useClickOutside(isMenuOpen, () => setIsMenuOpen(false), [menuRef, buttonRef]);

	const getBackgroundColor = () => {
		if (isMenuOpen) return "bg-zinc-900/95";
		return isIntersecting ? "bg-zinc-800/40" : "bg-zinc-800/70";
	};

	return (
		<header ref={headerRef}>
			<div
				ref={menuRef}
				className={`mx-auto sm:container fixed top-4 inset-x-4 sm:inset-x-0 z-50 rounded-2xl shadow-[inset_0_1px_1px_0_hsla(0,0%,100%,.15)] border border-white/10 backdrop-blur duration-200 ${getBackgroundColor()}`}
			>
				<div className="flex items-center justify-between p-6">
					<Link
						href="/"
						className="duration-200 text-zinc-300 hover:text-zinc-100"
					>
						<Hexagon className="w-6 h-6" />
					</Link>

					<DesktopNavigation />

					<button
						ref={buttonRef}
						className="md:hidden text-zinc-400 hover:text-zinc-100"
						onClick={() => setIsMenuOpen(!isMenuOpen)}
					>
						{isMenuOpen ? <X className="w-6 h-6" /> : <Menu className="w-6 h-6" />}
					</button>
				</div>

				<MobileNavigation isOpen={isMenuOpen} onClose={() => setIsMenuOpen(false)} />
			</div>
		</header>
	);
};
