// sveltekit/src/routes/profile/+page.svelte
<script lang="ts">
	import AnimatedTitle from '$components/AnimatedTitle.svelte';
	import ContentLayout from '$components/ContentLayout.svelte';

	let { data } = $props();
	let resume = $derived(data.resume);
	let technicalHighlights = $derived(resume.highlights?.technical ?? []);
	let experienceYears = $derived(resume.highlights?.numbers?.experience_years);
	let productsContributed = $derived(resume.highlights?.numbers?.products_contributed);
</script>

<svelte:head><title>Profile :: janigowski.dev</title></svelte:head>

<ContentLayout>
	<header class="relative isolate overflow-hidden">
		<div class="container relative isolate mx-auto overflow-hidden py-24 sm:py-32">
			<div class="mx-auto flex max-w-7xl flex-col items-center px-6 text-center lg:px-8">
				<div class="mx-auto max-w-2xl lg:mx-0">
					<AnimatedTitle text={resume.name} />
					<p class="mt-6 text-lg leading-8 text-zinc-400">{@html resume.role}</p>
					<div class="mt-6 flex justify-center gap-4 text-sm text-zinc-400">
						{#if experienceYears}
							<div class="rounded-md bg-zinc-800/50 px-3 py-1.5">
								<strong>{experienceYears}</strong> years of experience
							</div>
						{/if}
						{#if productsContributed}
							<div class="rounded-md bg-zinc-800/50 px-3 py-1.5">
								<strong>{productsContributed}</strong> products contributed
							</div>
						{/if}
					</div>
					<div class="mt-6 flex flex-wrap justify-center gap-2">
						{#each technicalHighlights as highlight}
							<span
								class="inline-block rounded bg-zinc-800/30 px-3 py-1.5 text-sm text-zinc-400"
							>
								{highlight}
							</span>
						{/each}
					</div>
				</div>
			</div>
		</div>
	</header>

	<div class="mx-auto max-w-7xl px-6 lg:px-8">
		<div class="mx-auto max-w-5xl">
			<div class="mb-16 grid grid-cols-1 gap-12 md:grid-cols-[2fr_1fr]">
				<div>
					<h2 class="mb-6 text-2xl font-bold text-zinc-100">About Me</h2>
					<div class="text-lg leading-relaxed text-zinc-300">{@html resume.summary}</div>
				</div>
				<div>
					<h2 class="mb-4 text-xl font-medium text-zinc-100">Clifton Strengths</h2>
					<div class="flex flex-wrap gap-2">
						{#each resume.clifton_strengths ?? [] as strength}
							<span
								class="inline-block rounded bg-zinc-800/20 px-3 py-1.5 text-sm text-zinc-400"
							>
								{strength}
							</span>
						{/each}
					</div>
				</div>
			</div>

			<section class="mb-16">
				<h2 class="mb-6 text-2xl font-bold text-zinc-100">Work Experience</h2>
				{#each resume.work ?? [] as job}
					<article class="mb-16">
						<div class="mb-2 flex flex-col justify-between md:flex-row">
							<h3 class="text-2xl font-semibold text-zinc-100">{job.position}</h3>
							<div class="text-zinc-400">
								{job.startDate} — {job.endDate || 'Present'}
							</div>
						</div>
						<div class="mb-6 text-xl text-zinc-400">{job.name}</div>
						<div class="flex flex-col gap-8 md:flex-row">
							<div class="md:w-2/3">
								{#if job.highlights}
									<div class="mb-6">
										<ul class="list-disc space-y-3 pl-5">
											{#each job.highlights as highlight}
												<li class="text-zinc-300">{@html highlight}</li>
											{/each}
										</ul>
									</div>
								{/if}
								{#if job.projects?.length}
									<div class="mb-6">
										<h4 class="mb-4 text-xl font-semibold text-zinc-200">Projects</h4>
										<div class="space-y-6">
											{#each job.projects as project}
												<div class="rounded-lg border border-zinc-700/50 bg-zinc-800/50 p-6">
													<h5 class="mb-2 text-lg font-medium text-zinc-100">
														{#if project.anchor}
															<a
																href={project.anchor}
																class="transition-colors duration-200 hover:text-zinc-300"
															>
																{project.name}
															</a>
														{:else}
															{project.name}
														{/if}
													</h5>
													{#if project.summary}
														<p class="mb-6 text-zinc-400">{project.summary}</p>
													{/if}
													{#if project.highlights}
														<ul class="list-disc space-y-2 pl-5">
															{#each project.highlights as highlight}
																<li class="text-zinc-300">{@html highlight}</li>
															{/each}
														</ul>
													{/if}
												</div>
											{/each}
										</div>
									</div>
								{/if}
							</div>
							{#if job.skills?.length}
								<div class="md:w-1/3">
									<div class="sticky top-24 rounded-lg border border-zinc-700/30 bg-zinc-800/30 p-5">
										<h4 class="mb-3 text-lg font-medium text-zinc-200">Skills</h4>
										<div class="flex flex-wrap gap-2">
											{#each job.skills as skill}
												<span
													class="inline-block rounded-full bg-zinc-800 px-3 py-1 text-sm text-zinc-300 transition-colors duration-200 hover:bg-zinc-700"
												>
													{skill}
												</span>
											{/each}
										</div>
									</div>
								</div>
							{/if}
						</div>
					</article>
				{/each}
			</section>

			<div class="flex flex-col gap-12 md:flex-row">
				<section class="md:w-1/2">
					<h2 class="mb-6 text-2xl font-bold text-zinc-100">Education</h2>
					{#each resume.education ?? [] as education}
						<div class="mb-4">
							<div class="flex flex-col justify-between md:flex-row">
								<h3 class="text-xl font-medium text-zinc-200">{education.institution}</h3>
								{#if education.year}
									<div class="whitespace-nowrap text-zinc-400">{education.year}</div>
								{/if}
							</div>
							<p class="text-zinc-300">{education.area}</p>
							<p class="text-zinc-400">{education.location}</p>
						</div>
					{/each}
				</section>
				<section class="flex-auto">
					<h2 class="mb-6 text-2xl font-bold text-zinc-100">Interests</h2>
					<div class="flex flex-wrap gap-2">
						{#each resume.interests ?? [] as interest}
							<span
								class="inline-block rounded-full bg-zinc-800 px-3 py-1 text-sm text-zinc-300"
							>
								{interest}
							</span>
						{/each}
					</div>
				</section>
			</div>
		</div>
	</div>
</ContentLayout>

// app/profile/page.tsx
import { Metadata } from "next";
import resumeData from "../../resume.json";
import Balancer from "react-wrap-balancer";
import AnimatedTitle from '../components/AnimatedTitle';

interface Project {
    name: string;
    summary?: string;
    highlights?: Array<string>;
    anchor?: string;
}

interface WorkExperience {
    name: string;
    position: string;
    startDate: string;
    endDate?: string;
    highlights: Array<string>;
    projects?: Array<Project>;
    skills: Array<string>;
}

interface Education {
    institution: string;
    area: string;
    year: string;
    location: string;
}

export const metadata: Metadata = {
    title: "Profile"
};

export default function ProfilePage() {
    const workExperience = resumeData.work;
    const education = resumeData.education;
    const cliftonStrengths = resumeData.clifton_strengths;
    const interests = resumeData.interests;
    const technicalHighlights = resumeData.highlights.technical;
    const experienceYears = resumeData.highlights.numbers.experience_years;
    const productsContributed = resumeData.highlights.numbers.products_contributed;

    return (
        <div className="relative min-h-screen">
            {/* Header Section */}
            <header className="relative isolate overflow-hidden">
                <div className="container mx-auto relative isolate overflow-hidden py-24 sm:py-32">
                    <div className="mx-auto max-w-7xl px-6 lg:px-8 text-center flex flex-col items-center">
                        <div className="mx-auto max-w-2xl lg:mx-0">
                            <AnimatedTitle text={resumeData.name} />
                            <p className="mt-6 text-lg leading-8 text-zinc-400">
                                <Balancer><span dangerouslySetInnerHTML={{ __html: resumeData.role }} /></Balancer>
                            </p>
                            <div className="mt-6 flex justify-center gap-4 text-zinc-400 text-sm">
                                <div className='bg-zinc-800/50 px-3 py-1.5 rounded-md'>
                                    <strong>{experienceYears}</strong> years of experience
                                </div>
                                <div className='bg-zinc-800/50 px-3 py-1.5 rounded-md'>
                                    <strong>{productsContributed}</strong> products contributed
                                </div>
                            </div>
                            <div className="mt-6 flex flex-wrap justify-center gap-2">
                                {technicalHighlights.map((highlight, index) => (
                                    <span key={index} className="inline-block px-3 py-1.5 bg-zinc-800/30 text-zinc-400 rounded text-sm">
                                        {highlight}
                                    </span>
                                ))}
                            </div>
                        </div>
                    </div>
                </div>
            </header>

            <div className="px-6 mx-auto max-w-7xl lg:px-8">
                <div className="max-w-5xl mx-auto">
                    {/* About Me and Clifton Strengths */}
                    <div className="mb-16 grid grid-cols-1 md:grid-cols-[2fr,1fr] gap-12">
                        <div>
                            <h2 className="text-2xl font-bold text-zinc-100 mb-6">About Me</h2>
                            <div className="text-lg text-zinc-300 leading-relaxed" dangerouslySetInnerHTML={{ __html: resumeData.summary }} />
                        </div>
                        <div>
                            <h2 className="text-xl font-medium text-zinc-100 mb-4">Clifton Strengths</h2>
                            <div className="flex flex-wrap gap-2">
                                {cliftonStrengths.map((strength, index) => (
                                    <span key={index} className="inline-block px-3 py-1.5 bg-zinc-800/20 text-zinc-400 rounded text-sm">
                                        {strength}
                                    </span>
                                ))}
                            </div>
                        </div>
                    </div>

                    {/* Work Experience */}
                    <div className="mb-16">
                        <h2 className="text-2xl font-bold text-zinc-100 mb-6">Work Experience</h2>
                        {workExperience.map((experience, index) => (
                            <div key={index} className="mb-16">
                                <div className="flex flex-col md:flex-row justify-between mb-2">
                                    <h3 className="text-2xl font-semibold text-zinc-100">{experience.position}</h3>
                                    <div className="text-zinc-400">
                                        {experience.startDate} — {experience.endDate || "Present"}
                                    </div>
                                </div>
                                <div className="text-xl text-zinc-400 mb-6">{experience.name}</div>

                                <div className="flex flex-col md:flex-row gap-8">
                                    <div className="md:w-2/3">
                                        <div className="mb-6">
                                            <ul className="space-y-3 list-disc pl-5">
                                                {experience.highlights.map((highlight, index) => (
                                                    <li key={index} className="text-zinc-300" dangerouslySetInnerHTML={{ __html: highlight }} />
                                                ))}
                                            </ul>
                                        </div>

                                        {experience.projects && experience.projects.length > 0 && (
                                            <div className="mb-6">
                                                <h4 className="text-xl font-semibold text-zinc-200 mb-4">Projects</h4>
                                                <div className="space-y-6">
                                                    {experience.projects.map((project: Project, index: number) => (
                                                        <div key={index} className="bg-zinc-800/50 p-6 rounded-lg border border-zinc-700/50">
                                                            <h5 className="text-lg font-medium text-zinc-100 mb-2">
                                                                {project.anchor ? (
                                                                    <a href={project.anchor} className="hover:text-zinc-300 transition-colors duration-200">{project.name}</a>
                                                                ) : (
                                                                    project.name
                                                                )}
                                                            </h5>
                                                            {project.summary && <p className="text-zinc-400 mb-6">{project.summary}</p>}
                                                            {project.highlights && (
                                                                <ul className="space-y-2 list-disc pl-5">
                                                                    {project.highlights.map((highlight: string, idx: number) => (
                                                                        <li key={idx} className="text-zinc-300" dangerouslySetInnerHTML={{ __html: highlight }} />
                                                                    ))}
                                                                </ul>
                                                            )}
                                                        </div>
                                                    ))}
                                                </div>
                                            </div>
                                        )}
                                    </div>

                                    <div className="md:w-1/3">
                                        <div className="bg-zinc-800/30 p-5 rounded-lg border border-zinc-700/30 sticky top-24">
                                            <h4 className="text-lg font-medium text-zinc-200 mb-3">Skills</h4>
                                            <div className="flex flex-wrap gap-2">
                                                {experience.skills.map((skill, index) => (
                                                    <span key={index} className="inline-block px-3 py-1 bg-zinc-800 text-zinc-300 rounded-full text-sm hover:bg-zinc-700 transition-colors duration-200">
                                                        {skill}
                                                    </span>
                                                ))}
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        ))}
                    </div>

                    {/* Education and Interests */}
                    <div className="flex flex-col md:flex-row gap-12">
                        <div className="w-1/2">
                            <h2 className="text-2xl font-bold text-zinc-100 mb-6">Education</h2>
                            {education.map((edu, index) => (
                                <div key={index} className="mb-4">
                                    <div className="flex flex-col md:flex-row justify-between">
                                        <h3 className="text-xl font-medium text-zinc-200">{edu.institution}</h3>
                                        <div className="text-zinc-400 whitespace-nowrap">{edu.year}</div>
                                    </div>
                                    <p className="text-zinc-300">{edu.area}</p>
                                    <p className="text-zinc-400">{edu.location}</p>
                                </div>
                            ))}
                        </div>
                        <div className="flex-auto">
                            <h2 className="text-2xl font-bold text-zinc-100 mb-6">Interests</h2>
                            <div className="flex flex-wrap gap-2">
                                {interests.map((interest, index) => (
                                    <span key={index} className="inline-block px-3 py-1 bg-zinc-800 text-zinc-300 rounded-full text-sm">
                                        {interest}
                                    </span>
                                ))}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    );
}
